/**
 * Explicit machine-readable permission codes (section 6). Business modules
 * added in later phases append their own `<module>.<resource>.<action>`
 * codes here/in their own module — never hardcode role names in logic.
 */
export const PermissionCodes = {
  CORE_USERS_VIEW: 'core.users.view',
  CORE_USERS_MANAGE: 'core.users.manage',
  CORE_ROLES_VIEW: 'core.roles.view',
  CORE_ROLES_MANAGE: 'core.roles.manage',
  CORE_TENANT_MANAGE: 'core.tenant.manage',
  CORE_SETTINGS_VIEW: 'core.settings.view',
  CORE_SETTINGS_MANAGE: 'core.settings.manage',

  DOCUMENTS_VIEW: 'documents.view',
  DOCUMENTS_CREATE: 'documents.create',
  DOCUMENTS_EDIT: 'documents.edit',
  DOCUMENTS_DELETE: 'documents.delete',
  DOCUMENTS_POST: 'documents.post',
  DOCUMENTS_UNPOST: 'documents.unpost',
  DOCUMENTS_CANCEL: 'documents.cancel',

  PERIODS_VIEW: 'periods.view',
  PERIODS_CLOSE: 'periods.close',
  PERIODS_REOPEN: 'periods.reopen',

  AUDIT_VIEW: 'audit.view',

  CURRENCY_MANAGE: 'currency.manage',
  NUMBERING_MANAGE: 'numbering.manage',

  // Phase 1 — Organization & Business Structure (section 34)
  ORGANIZATION_VIEW: 'organization.view',
  ORGANIZATION_CREATE: 'organization.create',
  ORGANIZATION_EDIT: 'organization.edit',
  ORGANIZATION_DEACTIVATE: 'organization.deactivate',

  BRANCH_VIEW: 'branch.view',
  BRANCH_CREATE: 'branch.create',
  BRANCH_EDIT: 'branch.edit',
  BRANCH_DEACTIVATE: 'branch.deactivate',

  DEPARTMENT_VIEW: 'department.view',
  DEPARTMENT_CREATE: 'department.create',
  DEPARTMENT_EDIT: 'department.edit',
  DEPARTMENT_DEACTIVATE: 'department.deactivate',

  RESPONSIBLE_PERSON_VIEW: 'responsible_person.view',
  RESPONSIBLE_PERSON_MANAGE: 'responsible_person.manage',

  WAREHOUSE_VIEW: 'warehouse.view',
  WAREHOUSE_CREATE: 'warehouse.create',
  WAREHOUSE_EDIT: 'warehouse.edit',
  WAREHOUSE_DEACTIVATE: 'warehouse.deactivate',

  CASHBOX_VIEW: 'cashbox.view',
  CASHBOX_CREATE: 'cashbox.create',
  CASHBOX_EDIT: 'cashbox.edit',
  CASHBOX_DEACTIVATE: 'cashbox.deactivate',

  BANK_ACCOUNT_VIEW: 'bank_account.view',
  BANK_ACCOUNT_CREATE: 'bank_account.create',
  BANK_ACCOUNT_EDIT: 'bank_account.edit',
  BANK_ACCOUNT_DEACTIVATE: 'bank_account.deactivate',

  ACCOUNTING_POLICY_VIEW: 'accounting_policy.view',
  ACCOUNTING_POLICY_MANAGE: 'accounting_policy.manage',

  TAX_PROFILE_VIEW: 'tax_profile.view',
  TAX_PROFILE_MANAGE: 'tax_profile.manage',

  ORGANIZATION_ACCESS_MANAGE: 'organization_access.manage',

  // Phase 2 — Product/Nomenclature master data
  UNIT_OF_MEASURE_VIEW: 'unit_of_measure.view',
  UNIT_OF_MEASURE_CREATE: 'unit_of_measure.create',
  UNIT_OF_MEASURE_EDIT: 'unit_of_measure.edit',
  UNIT_OF_MEASURE_DEACTIVATE: 'unit_of_measure.deactivate',

  PRODUCT_CATEGORY_VIEW: 'product_category.view',
  PRODUCT_CATEGORY_CREATE: 'product_category.create',
  PRODUCT_CATEGORY_EDIT: 'product_category.edit',
  PRODUCT_CATEGORY_DEACTIVATE: 'product_category.deactivate',

  PRODUCT_VIEW: 'product.view',
  PRODUCT_CREATE: 'product.create',
  PRODUCT_EDIT: 'product.edit',
  PRODUCT_DEACTIVATE: 'product.deactivate',

  // Phase 3 — Counterparty Master Data + Pricing
  UNIT_CONVERSION_VIEW: 'unit_conversion.view',
  UNIT_CONVERSION_CREATE: 'unit_conversion.create',
  UNIT_CONVERSION_EDIT: 'unit_conversion.edit',
  UNIT_CONVERSION_DEACTIVATE: 'unit_conversion.deactivate',

  COUNTERPARTY_VIEW: 'counterparty.view',
  COUNTERPARTY_CREATE: 'counterparty.create',
  COUNTERPARTY_EDIT: 'counterparty.edit',
  COUNTERPARTY_DEACTIVATE: 'counterparty.deactivate',
  COUNTERPARTY_APPROVE: 'counterparty.approve',

  // Counterparty contracts / amendments / documents ("Kontragentlər" module)
  CONTRACT_VIEW: 'contract.view',
  CONTRACT_CREATE: 'contract.create',
  CONTRACT_EDIT: 'contract.edit',
  CONTRACT_APPROVE: 'contract.approve',
  CONTRACT_AMENDMENT_CREATE: 'contract.amendment.create',
  CONTRACT_AMENDMENT_EDIT: 'contract.amendment.edit',
  CONTRACT_AMENDMENT_APPROVE: 'contract.amendment.approve',
  CONTRACT_DOCUMENT_MANAGE: 'contract.document.manage',

  PRICE_LIST_VIEW: 'price_list.view',
  PRICE_LIST_CREATE: 'price_list.create',
  PRICE_LIST_EDIT: 'price_list.edit',
  PRICE_LIST_DEACTIVATE: 'price_list.deactivate',

  PRODUCT_PRICE_VIEW: 'product_price.view',
  PRODUCT_PRICE_MANAGE: 'product_price.manage',

  // Phase 4 — Sales documents (orders + invoices)
  SALES_ORDER_VIEW: 'sales_order.view',
  SALES_ORDER_CREATE: 'sales_order.create',
  SALES_ORDER_EDIT: 'sales_order.edit',

  SALES_INVOICE_VIEW: 'sales_invoice.view',
  SALES_INVOICE_CREATE: 'sales_invoice.create',
  SALES_INVOICE_EDIT: 'sales_invoice.edit',

  // Accounting Core (docx spec Phase 4, section 100)
  ACCOUNTING_CHART_VIEW: 'accounting.chart.view',
  ACCOUNTING_CHART_MANAGE: 'accounting.chart.manage',
  ACCOUNTING_ACCOUNT_VIEW: 'accounting.account.view',
  ACCOUNTING_ACCOUNT_CREATE: 'accounting.account.create',
  ACCOUNTING_ACCOUNT_EDIT: 'accounting.account.edit',
  ACCOUNTING_ACCOUNT_DEACTIVATE: 'accounting.account.deactivate',
  ACCOUNTING_DIMENSION_VIEW: 'accounting.dimension.view',
  ACCOUNTING_DIMENSION_MANAGE: 'accounting.dimension.manage',
  ACCOUNTING_MAPPING_VIEW: 'accounting.mapping.view',
  ACCOUNTING_MAPPING_MANAGE: 'accounting.mapping.manage',
  ACCOUNTING_JOURNAL_VIEW: 'accounting.journal.view',
  ACCOUNTING_JOURNAL_POST: 'accounting.journal.post',
  ACCOUNTING_JOURNAL_UNPOST: 'accounting.journal.unpost',
  ACCOUNTING_JOURNAL_REVERSE: 'accounting.journal.reverse',
  ACCOUNTING_MANUAL_OPERATION_VIEW: 'accounting.manual_operation.view',
  ACCOUNTING_MANUAL_OPERATION_CREATE: 'accounting.manual_operation.create',
  ACCOUNTING_MANUAL_OPERATION_EDIT: 'accounting.manual_operation.edit',
  ACCOUNTING_MANUAL_OPERATION_POST: 'accounting.manual_operation.post',
  ACCOUNTING_MANUAL_OPERATION_UNPOST: 'accounting.manual_operation.unpost',
  ACCOUNTING_OPENING_BALANCE_VIEW: 'accounting.opening_balance.view',
  ACCOUNTING_OPENING_BALANCE_MANAGE: 'accounting.opening_balance.manage',
  ACCOUNTING_POSTING_HISTORY_VIEW: 'accounting.posting_history.view',
  ACCOUNTING_TRIAL_BALANCE_VIEW: 'accounting.trial_balance.view',
  ACCOUNTING_GENERAL_LEDGER_VIEW: 'accounting.general_ledger.view',

  // Tax Engine (docx spec Phase 5, section 97)
  TAX_CONFIG_VIEW: 'tax.config.view',
  TAX_RULE_VIEW: 'tax.rule.view',
  TAX_RULE_CREATE: 'tax.rule.create',
  TAX_RULE_EDIT: 'tax.rule.edit',
  TAX_RULE_APPROVE: 'tax.rule.approve',
  TAX_RULE_ACTIVATE: 'tax.rule.activate',
  TAX_RATE_VIEW: 'tax.rate.view',
  TAX_RATE_MANAGE: 'tax.rate.manage',
  TAX_CATEGORY_VIEW: 'tax.category.view',
  TAX_CATEGORY_MANAGE: 'tax.category.manage',
  TAX_REGISTRATION_VIEW: 'tax.registration.view',
  TAX_REGISTRATION_MANAGE: 'tax.registration.manage',
  TAX_MAPPING_VIEW: 'tax.mapping.view',
  TAX_MAPPING_MANAGE: 'tax.mapping.manage',
  TAX_LEGAL_SOURCE_VIEW: 'tax.legal_source.view',
  TAX_LEGAL_SOURCE_MANAGE: 'tax.legal_source.manage',
  TAX_CALCULATION_VIEW: 'tax.calculation.view',
  TAX_REGISTER_VIEW: 'tax.register.view',
  TAX_OVERRIDE: 'tax.override',
  TAX_PERIOD_VIEW: 'tax.period.view',
  TAX_PERIOD_MANAGE: 'tax.period.manage',

  // Sales Pre-Order & Order Management (docx spec Phase 6, section 100)
  SALES_CUSTOMER_REQUEST_VIEW: 'sales.customer_request.view',
  SALES_CUSTOMER_REQUEST_CREATE: 'sales.customer_request.create',
  SALES_CUSTOMER_REQUEST_EDIT: 'sales.customer_request.edit',
  SALES_CUSTOMER_REQUEST_CANCEL: 'sales.customer_request.cancel',
  SALES_OFFER_VIEW: 'sales.offer.view',
  SALES_OFFER_CREATE: 'sales.offer.create',
  SALES_OFFER_EDIT: 'sales.offer.edit',
  SALES_OFFER_SEND: 'sales.offer.send',
  SALES_OFFER_ACCEPT: 'sales.offer.accept',
  SALES_OFFER_CANCEL: 'sales.offer.cancel',
  SALES_OFFER_CONVERT: 'sales.offer.convert',
  SALES_ORDER_CONFIRM: 'sales.order.confirm',
  SALES_ORDER_CANCEL: 'sales.order.cancel',
  SALES_ORDER_REOPEN: 'sales.order.reopen',
  SALES_PRICE_OVERRIDE: 'sales.price.override',
  SALES_DISCOUNT_OVERRIDE: 'sales.discount.override',
  SALES_CREDIT_OVERRIDE: 'sales.credit.override',
  SALES_RESERVATION_VIEW: 'sales.reservation.view',
  SALES_RESERVATION_MANAGE: 'sales.reservation.manage',
  SALES_SHIPMENT_PLAN_VIEW: 'sales.shipment_plan.view',
  SALES_SHIPMENT_PLAN_MANAGE: 'sales.shipment_plan.manage',
  SALES_PAYMENT_SCHEDULE_VIEW: 'sales.payment_schedule.view',
  SALES_FULFILLMENT_VIEW: 'sales.fulfillment.view',
  SALES_ORDER_HOLD_MANAGE: 'sales.order_hold.manage',

  // Sales Execution (docx spec Phase 7, section 84)
  SALES_SHIPMENT_VIEW: 'sales.shipment.view',
  SALES_SHIPMENT_CREATE: 'sales.shipment.create',
  SALES_SHIPMENT_EDIT: 'sales.shipment.edit',
  SALES_SHIPMENT_CANCEL: 'sales.shipment.cancel',
  SALES_INVOICE_REVERSE: 'sales.invoice.reverse',
  SALES_RETURN_VIEW: 'sales.return.view',
  SALES_RETURN_CREATE: 'sales.return.create',
  SALES_RETURN_EDIT: 'sales.return.edit',
  SALES_ACCOUNTING_ENTRIES_VIEW: 'sales.accounting_entries.view',
  SALES_TAX_DETAILS_VIEW: 'sales.tax_details.view',

  // Procurement & Purchase Order Management (docx spec Phase 8, section 92)
  PURCHASE_REQUIREMENT_VIEW: 'purchase.requirement.view',
  PURCHASE_REQUIREMENT_CREATE: 'purchase.requirement.create',
  PURCHASE_REQUIREMENT_EDIT: 'purchase.requirement.edit',
  PURCHASE_REQUIREMENT_CANCEL: 'purchase.requirement.cancel',
  PURCHASE_REQUIREMENT_APPROVE: 'purchase.requirement.approve',
  PURCHASE_REQUIREMENT_REJECT: 'purchase.requirement.reject',
  PURCHASE_ORDER_VIEW: 'purchase.order.view',
  PURCHASE_ORDER_CREATE: 'purchase.order.create',
  PURCHASE_ORDER_EDIT: 'purchase.order.edit',
  PURCHASE_ORDER_APPROVE: 'purchase.order.approve',
  PURCHASE_ORDER_REJECT: 'purchase.order.reject',
  PURCHASE_ORDER_CONFIRM: 'purchase.order.confirm',
  PURCHASE_ORDER_REOPEN: 'purchase.order.reopen',
  PURCHASE_ORDER_CANCEL: 'purchase.order.cancel',
  PURCHASE_PRICE_OVERRIDE: 'purchase.price.override',
  PURCHASE_SUPPLIER_SELECTION_VIEW: 'purchase.supplier_selection.view',
  PURCHASE_SUPPLIER_SELECTION_MANAGE: 'purchase.supplier_selection.manage',
  PURCHASE_EXPECTED_RECEIPT_VIEW: 'purchase.expected_receipt.view',
  PURCHASE_PAYMENT_SCHEDULE_VIEW: 'purchase.payment_schedule.view',
  PURCHASE_PAYMENT_SCHEDULE_MANAGE: 'purchase.payment_schedule.manage',
  PURCHASE_SUPPLY_PLANNING_VIEW: 'purchase.supply_planning.view',
  PURCHASE_SUPPLY_PEGGING_MANAGE: 'purchase.supply_pegging.manage',
  PURCHASE_ORDER_HOLD_MANAGE: 'purchase.order_hold.manage',
  PURCHASE_SUPPLIER_PRODUCT_CODE_VIEW: 'purchase.supplier_product_code.view',
  PURCHASE_SUPPLIER_PRODUCT_CODE_MANAGE: 'purchase.supplier_product_code.manage',

  // Purchase Execution (docx spec Phase 9, section 37) — Goods Receipt,
  // Purchase Invoice, Purchase Return, Additional Purchase Cost. Confirm
  // /reopen/cancel reuse the generic documents.post/unpost/cancel
  // permissions on /documents/<TYPE>/:id/... like every other document
  // type in this codebase (PURCHASE_POST/UNPOST/CANCEL from the spec's
  // own list are intentionally not duplicated here).
  PURCHASE_VIEW: 'purchase_execution.view',
  PURCHASE_CREATE: 'purchase_execution.create',
  PURCHASE_EDIT: 'purchase_execution.edit',
  PURCHASE_RETURN: 'purchase_execution.return',
  PURCHASE_VIEW_ACCOUNTING: 'purchase_execution.view_accounting',
  // Approval workflow increment 2 (docs/APPROVALS.md): price/tax
  // visibility gate on Goods Receipt, plus approve/reject for the
  // over-delivery (WAREHOUSE_SUPERVISOR) and price-variance (ACCOUNTING)
  // approval steps.
  PURCHASE_PRICE_VIEW: 'purchase_execution.price_view',
  PURCHASE_RECEIPT_APPROVE: 'purchase_execution.receipt.approve',
  PURCHASE_RECEIPT_REJECT: 'purchase_execution.receipt.reject',
  PURCHASE_INVOICE_APPROVE: 'purchase_execution.invoice.approve',
  PURCHASE_INVOICE_REJECT: 'purchase_execution.invoice.reject',

  // Treasury / payment chain (docs/APPROVALS.md)
  PAYMENT_REQUEST_VIEW: 'treasury.payment_request.view',
  PAYMENT_REQUEST_CREATE: 'treasury.payment_request.create',
  PAYMENT_REQUEST_CANCEL: 'treasury.payment_request.cancel',
  PAYMENT_ORDER_VIEW: 'treasury.payment_order.view',
  PAYMENT_ORDER_CREATE: 'treasury.payment_order.create',
  PAYMENT_ORDER_EDIT: 'treasury.payment_order.edit',
  PAYMENT_ORDER_APPROVE: 'treasury.payment_order.approve',
  PAYMENT_ORDER_REJECT: 'treasury.payment_order.reject',
  PAYMENT_ORDER_RECONCILE: 'treasury.payment_order.reconcile',

  // Warehouse / Stock Engine (docx spec Phase 10, section 65)
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_VIEW_ALL_WAREHOUSES: 'inventory.view_all_warehouses',
  INVENTORY_TRANSFER_CREATE: 'inventory.transfer.create',
  INVENTORY_TRANSFER_POST: 'inventory.transfer.post',
  INVENTORY_TRANSFER_RECEIVE: 'inventory.transfer.receive',
  INVENTORY_INTERNAL_MOVE: 'inventory.internal_move',
  INVENTORY_CONSUME: 'inventory.consume',
  INVENTORY_WRITE_OFF: 'inventory.write_off',
  INVENTORY_WRITE_OFF_APPROVE: 'inventory.write_off.approve',
  INVENTORY_STATUS_CHANGE: 'inventory.status_change',
  INVENTORY_RESERVE: 'inventory.reserve',
  INVENTORY_RELEASE_RESERVATION: 'inventory.release_reservation',
  INVENTORY_OVERRIDE_NEGATIVE: 'inventory.override_negative',
  INVENTORY_VIEW_SERIAL_HISTORY: 'inventory.view_serial_history',
  INVENTORY_VIEW_MOVEMENTS: 'inventory.view_movements',
  INVENTORY_UNPOST: 'inventory.unpost',
  INVENTORY_PERIOD_OVERRIDE: 'inventory.period_override',
  INVENTORY_MANUAL_ADJUSTMENT: 'inventory.manual_adjustment',
} as const;

export const ALL_PERMISSION_CODES: { code: string; module: string; description: string }[] = [
  { code: PermissionCodes.CORE_USERS_VIEW, module: 'core', description: 'View users in the tenant' },
  { code: PermissionCodes.CORE_USERS_MANAGE, module: 'core', description: 'Manage tenant memberships' },
  { code: PermissionCodes.CORE_ROLES_VIEW, module: 'core', description: 'View roles and permissions' },
  { code: PermissionCodes.CORE_ROLES_MANAGE, module: 'core', description: 'Manage roles and role permissions' },
  { code: PermissionCodes.CORE_TENANT_MANAGE, module: 'core', description: 'Manage tenant-level configuration' },
  { code: PermissionCodes.CORE_SETTINGS_VIEW, module: 'core', description: 'View scoped settings' },
  { code: PermissionCodes.CORE_SETTINGS_MANAGE, module: 'core', description: 'Manage scoped settings' },

  { code: PermissionCodes.DOCUMENTS_VIEW, module: 'documents', description: 'View documents' },
  { code: PermissionCodes.DOCUMENTS_CREATE, module: 'documents', description: 'Create documents' },
  { code: PermissionCodes.DOCUMENTS_EDIT, module: 'documents', description: 'Edit documents' },
  { code: PermissionCodes.DOCUMENTS_DELETE, module: 'documents', description: 'Mark documents for deletion' },
  { code: PermissionCodes.DOCUMENTS_POST, module: 'documents', description: 'Post documents' },
  { code: PermissionCodes.DOCUMENTS_UNPOST, module: 'documents', description: 'Unpost documents' },
  { code: PermissionCodes.DOCUMENTS_CANCEL, module: 'documents', description: 'Cancel documents' },

  { code: PermissionCodes.PERIODS_VIEW, module: 'periods', description: 'View accounting periods' },
  { code: PermissionCodes.PERIODS_CLOSE, module: 'periods', description: 'Close accounting periods' },
  { code: PermissionCodes.PERIODS_REOPEN, module: 'periods', description: 'Reopen accounting periods' },

  { code: PermissionCodes.AUDIT_VIEW, module: 'audit', description: 'View audit events' },

  { code: PermissionCodes.CURRENCY_MANAGE, module: 'currency', description: 'Manage currencies and exchange rates' },
  { code: PermissionCodes.NUMBERING_MANAGE, module: 'numbering', description: 'Manage numbering sequences' },

  { code: PermissionCodes.ORGANIZATION_VIEW, module: 'organization', description: 'View organizations' },
  { code: PermissionCodes.ORGANIZATION_CREATE, module: 'organization', description: 'Create organizations' },
  { code: PermissionCodes.ORGANIZATION_EDIT, module: 'organization', description: 'Edit organizations' },
  { code: PermissionCodes.ORGANIZATION_DEACTIVATE, module: 'organization', description: 'Deactivate organizations' },

  { code: PermissionCodes.BRANCH_VIEW, module: 'branch', description: 'View branches' },
  { code: PermissionCodes.BRANCH_CREATE, module: 'branch', description: 'Create branches' },
  { code: PermissionCodes.BRANCH_EDIT, module: 'branch', description: 'Edit branches' },
  { code: PermissionCodes.BRANCH_DEACTIVATE, module: 'branch', description: 'Deactivate branches' },

  { code: PermissionCodes.DEPARTMENT_VIEW, module: 'department', description: 'View departments' },
  { code: PermissionCodes.DEPARTMENT_CREATE, module: 'department', description: 'Create departments' },
  { code: PermissionCodes.DEPARTMENT_EDIT, module: 'department', description: 'Edit departments' },
  { code: PermissionCodes.DEPARTMENT_DEACTIVATE, module: 'department', description: 'Deactivate departments' },

  { code: PermissionCodes.RESPONSIBLE_PERSON_VIEW, module: 'responsible_person', description: 'View responsible persons' },
  { code: PermissionCodes.RESPONSIBLE_PERSON_MANAGE, module: 'responsible_person', description: 'Manage responsible persons' },

  { code: PermissionCodes.WAREHOUSE_VIEW, module: 'warehouse', description: 'View warehouses' },
  { code: PermissionCodes.WAREHOUSE_CREATE, module: 'warehouse', description: 'Create warehouses' },
  { code: PermissionCodes.WAREHOUSE_EDIT, module: 'warehouse', description: 'Edit warehouses' },
  { code: PermissionCodes.WAREHOUSE_DEACTIVATE, module: 'warehouse', description: 'Deactivate warehouses' },

  { code: PermissionCodes.CASHBOX_VIEW, module: 'cashbox', description: 'View cashboxes' },
  { code: PermissionCodes.CASHBOX_CREATE, module: 'cashbox', description: 'Create cashboxes' },
  { code: PermissionCodes.CASHBOX_EDIT, module: 'cashbox', description: 'Edit cashboxes' },
  { code: PermissionCodes.CASHBOX_DEACTIVATE, module: 'cashbox', description: 'Deactivate cashboxes' },

  { code: PermissionCodes.BANK_ACCOUNT_VIEW, module: 'bank_account', description: 'View bank accounts' },
  { code: PermissionCodes.BANK_ACCOUNT_CREATE, module: 'bank_account', description: 'Create bank accounts' },
  { code: PermissionCodes.BANK_ACCOUNT_EDIT, module: 'bank_account', description: 'Edit bank accounts' },
  { code: PermissionCodes.BANK_ACCOUNT_DEACTIVATE, module: 'bank_account', description: 'Deactivate bank accounts' },

  { code: PermissionCodes.ACCOUNTING_POLICY_VIEW, module: 'accounting_policy', description: 'View accounting policies' },
  { code: PermissionCodes.ACCOUNTING_POLICY_MANAGE, module: 'accounting_policy', description: 'Manage accounting policies' },

  { code: PermissionCodes.TAX_PROFILE_VIEW, module: 'tax_profile', description: 'View tax profiles' },
  { code: PermissionCodes.TAX_PROFILE_MANAGE, module: 'tax_profile', description: 'Manage tax profiles' },

  { code: PermissionCodes.ORGANIZATION_ACCESS_MANAGE, module: 'organization_access', description: 'Grant/revoke organization access' },

  { code: PermissionCodes.UNIT_OF_MEASURE_VIEW, module: 'unit_of_measure', description: 'View units of measure' },
  { code: PermissionCodes.UNIT_OF_MEASURE_CREATE, module: 'unit_of_measure', description: 'Create units of measure' },
  { code: PermissionCodes.UNIT_OF_MEASURE_EDIT, module: 'unit_of_measure', description: 'Edit units of measure' },
  { code: PermissionCodes.UNIT_OF_MEASURE_DEACTIVATE, module: 'unit_of_measure', description: 'Deactivate units of measure' },

  { code: PermissionCodes.PRODUCT_CATEGORY_VIEW, module: 'product_category', description: 'View product categories' },
  { code: PermissionCodes.PRODUCT_CATEGORY_CREATE, module: 'product_category', description: 'Create product categories' },
  { code: PermissionCodes.PRODUCT_CATEGORY_EDIT, module: 'product_category', description: 'Edit product categories' },
  { code: PermissionCodes.PRODUCT_CATEGORY_DEACTIVATE, module: 'product_category', description: 'Deactivate product categories' },

  { code: PermissionCodes.PRODUCT_VIEW, module: 'product', description: 'View products' },
  { code: PermissionCodes.PRODUCT_CREATE, module: 'product', description: 'Create products' },
  { code: PermissionCodes.PRODUCT_EDIT, module: 'product', description: 'Edit products' },
  { code: PermissionCodes.PRODUCT_DEACTIVATE, module: 'product', description: 'Deactivate products' },

  { code: PermissionCodes.UNIT_CONVERSION_VIEW, module: 'unit_conversion', description: 'View unit conversions' },
  { code: PermissionCodes.UNIT_CONVERSION_CREATE, module: 'unit_conversion', description: 'Create unit conversions' },
  { code: PermissionCodes.UNIT_CONVERSION_EDIT, module: 'unit_conversion', description: 'Edit unit conversions' },
  { code: PermissionCodes.UNIT_CONVERSION_DEACTIVATE, module: 'unit_conversion', description: 'Deactivate unit conversions' },

  { code: PermissionCodes.COUNTERPARTY_VIEW, module: 'counterparty', description: 'View counterparties' },
  { code: PermissionCodes.COUNTERPARTY_CREATE, module: 'counterparty', description: 'Create counterparties' },
  { code: PermissionCodes.COUNTERPARTY_EDIT, module: 'counterparty', description: 'Edit counterparties' },
  { code: PermissionCodes.COUNTERPARTY_DEACTIVATE, module: 'counterparty', description: 'Deactivate counterparties' },
  { code: PermissionCodes.COUNTERPARTY_APPROVE, module: 'counterparty', description: 'Approve counterparties' },

  { code: PermissionCodes.CONTRACT_VIEW, module: 'contract', description: 'View counterparty contracts' },
  { code: PermissionCodes.CONTRACT_CREATE, module: 'contract', description: 'Create counterparty contracts' },
  { code: PermissionCodes.CONTRACT_EDIT, module: 'contract', description: 'Edit counterparty contracts' },
  { code: PermissionCodes.CONTRACT_APPROVE, module: 'contract', description: 'Approve counterparty contracts' },
  { code: PermissionCodes.CONTRACT_AMENDMENT_CREATE, module: 'contract', description: 'Create contract amendments' },
  { code: PermissionCodes.CONTRACT_AMENDMENT_EDIT, module: 'contract', description: 'Edit contract amendments' },
  { code: PermissionCodes.CONTRACT_AMENDMENT_APPROVE, module: 'contract', description: 'Approve contract amendments' },
  { code: PermissionCodes.CONTRACT_DOCUMENT_MANAGE, module: 'contract', description: 'Upload/download/delete contract and amendment documents' },

  { code: PermissionCodes.PRICE_LIST_VIEW, module: 'price_list', description: 'View price lists' },
  { code: PermissionCodes.PRICE_LIST_CREATE, module: 'price_list', description: 'Create price lists' },
  { code: PermissionCodes.PRICE_LIST_EDIT, module: 'price_list', description: 'Edit price lists' },
  { code: PermissionCodes.PRICE_LIST_DEACTIVATE, module: 'price_list', description: 'Deactivate price lists' },

  { code: PermissionCodes.PRODUCT_PRICE_VIEW, module: 'product_price', description: 'View product prices' },
  { code: PermissionCodes.PRODUCT_PRICE_MANAGE, module: 'product_price', description: 'Manage product prices' },

  { code: PermissionCodes.SALES_ORDER_VIEW, module: 'sales_order', description: 'View sales orders' },
  { code: PermissionCodes.SALES_ORDER_CREATE, module: 'sales_order', description: 'Create sales orders' },
  { code: PermissionCodes.SALES_ORDER_EDIT, module: 'sales_order', description: 'Edit sales orders' },

  { code: PermissionCodes.SALES_INVOICE_VIEW, module: 'sales_invoice', description: 'View sales invoices' },
  { code: PermissionCodes.SALES_INVOICE_CREATE, module: 'sales_invoice', description: 'Create sales invoices' },
  { code: PermissionCodes.SALES_INVOICE_EDIT, module: 'sales_invoice', description: 'Edit sales invoices' },

  { code: PermissionCodes.ACCOUNTING_CHART_VIEW, module: 'accounting', description: 'View the chart of accounts' },
  { code: PermissionCodes.ACCOUNTING_CHART_MANAGE, module: 'accounting', description: 'Adopt/manage charts of accounts' },
  { code: PermissionCodes.ACCOUNTING_ACCOUNT_VIEW, module: 'accounting', description: 'View accounts' },
  { code: PermissionCodes.ACCOUNTING_ACCOUNT_CREATE, module: 'accounting', description: 'Create accounts/subaccounts' },
  { code: PermissionCodes.ACCOUNTING_ACCOUNT_EDIT, module: 'accounting', description: 'Edit accounts' },
  { code: PermissionCodes.ACCOUNTING_ACCOUNT_DEACTIVATE, module: 'accounting', description: 'Deactivate accounts' },
  { code: PermissionCodes.ACCOUNTING_DIMENSION_VIEW, module: 'accounting', description: 'View accounting dimensions' },
  { code: PermissionCodes.ACCOUNTING_DIMENSION_MANAGE, module: 'accounting', description: 'Manage accounting dimensions/rules' },
  { code: PermissionCodes.ACCOUNTING_MAPPING_VIEW, module: 'accounting', description: 'View accounting mappings' },
  { code: PermissionCodes.ACCOUNTING_MAPPING_MANAGE, module: 'accounting', description: 'Manage accounting mappings' },
  { code: PermissionCodes.ACCOUNTING_JOURNAL_VIEW, module: 'accounting', description: 'View journal entries' },
  { code: PermissionCodes.ACCOUNTING_JOURNAL_POST, module: 'accounting', description: 'Post journal entries' },
  { code: PermissionCodes.ACCOUNTING_JOURNAL_UNPOST, module: 'accounting', description: 'Unpost journal entries' },
  { code: PermissionCodes.ACCOUNTING_JOURNAL_REVERSE, module: 'accounting', description: 'Reverse posted journal entries' },
  { code: PermissionCodes.ACCOUNTING_MANUAL_OPERATION_VIEW, module: 'accounting', description: 'View manual operations' },
  { code: PermissionCodes.ACCOUNTING_MANUAL_OPERATION_CREATE, module: 'accounting', description: 'Create manual operations' },
  { code: PermissionCodes.ACCOUNTING_MANUAL_OPERATION_EDIT, module: 'accounting', description: 'Edit draft manual operations' },
  { code: PermissionCodes.ACCOUNTING_MANUAL_OPERATION_POST, module: 'accounting', description: 'Post manual operations' },
  { code: PermissionCodes.ACCOUNTING_MANUAL_OPERATION_UNPOST, module: 'accounting', description: 'Unpost manual operations' },
  { code: PermissionCodes.ACCOUNTING_OPENING_BALANCE_VIEW, module: 'accounting', description: 'View opening balances' },
  { code: PermissionCodes.ACCOUNTING_OPENING_BALANCE_MANAGE, module: 'accounting', description: 'Enter opening balances' },
  { code: PermissionCodes.ACCOUNTING_POSTING_HISTORY_VIEW, module: 'accounting', description: 'View posting run history' },
  { code: PermissionCodes.ACCOUNTING_TRIAL_BALANCE_VIEW, module: 'accounting', description: 'View the trial balance' },
  { code: PermissionCodes.ACCOUNTING_GENERAL_LEDGER_VIEW, module: 'accounting', description: 'View the general ledger' },

  { code: PermissionCodes.TAX_CONFIG_VIEW, module: 'tax', description: 'View tax configuration' },
  { code: PermissionCodes.TAX_RULE_VIEW, module: 'tax', description: 'View tax rules' },
  { code: PermissionCodes.TAX_RULE_CREATE, module: 'tax', description: 'Create tax rules' },
  { code: PermissionCodes.TAX_RULE_EDIT, module: 'tax', description: 'Edit tax rules' },
  { code: PermissionCodes.TAX_RULE_APPROVE, module: 'tax', description: 'Approve tax rules' },
  { code: PermissionCodes.TAX_RULE_ACTIVATE, module: 'tax', description: 'Activate tax rules' },
  { code: PermissionCodes.TAX_RATE_VIEW, module: 'tax', description: 'View tax rates' },
  { code: PermissionCodes.TAX_RATE_MANAGE, module: 'tax', description: 'Manage tax rates' },
  { code: PermissionCodes.TAX_CATEGORY_VIEW, module: 'tax', description: 'View tax categories' },
  { code: PermissionCodes.TAX_CATEGORY_MANAGE, module: 'tax', description: 'Manage tax categories' },
  { code: PermissionCodes.TAX_REGISTRATION_VIEW, module: 'tax', description: 'View tax registrations' },
  { code: PermissionCodes.TAX_REGISTRATION_MANAGE, module: 'tax', description: 'Manage tax registrations' },
  { code: PermissionCodes.TAX_MAPPING_VIEW, module: 'tax', description: 'View tax accounting mappings' },
  { code: PermissionCodes.TAX_MAPPING_MANAGE, module: 'tax', description: 'Manage tax accounting mappings' },
  { code: PermissionCodes.TAX_LEGAL_SOURCE_VIEW, module: 'tax', description: 'View tax legal sources' },
  { code: PermissionCodes.TAX_LEGAL_SOURCE_MANAGE, module: 'tax', description: 'Manage tax legal sources' },
  { code: PermissionCodes.TAX_CALCULATION_VIEW, module: 'tax', description: 'Preview/calculate tax' },
  { code: PermissionCodes.TAX_REGISTER_VIEW, module: 'tax', description: 'View the tax register' },
  { code: PermissionCodes.TAX_OVERRIDE, module: 'tax', description: 'Override a calculated tax amount' },
  { code: PermissionCodes.TAX_PERIOD_VIEW, module: 'tax', description: 'View tax periods' },
  { code: PermissionCodes.TAX_PERIOD_MANAGE, module: 'tax', description: 'Manage tax periods' },

  { code: PermissionCodes.SALES_CUSTOMER_REQUEST_VIEW, module: 'sales_preorder', description: 'View customer requests' },
  { code: PermissionCodes.SALES_CUSTOMER_REQUEST_CREATE, module: 'sales_preorder', description: 'Create customer requests' },
  { code: PermissionCodes.SALES_CUSTOMER_REQUEST_EDIT, module: 'sales_preorder', description: 'Edit customer requests' },
  { code: PermissionCodes.SALES_CUSTOMER_REQUEST_CANCEL, module: 'sales_preorder', description: 'Cancel customer requests' },
  { code: PermissionCodes.SALES_OFFER_VIEW, module: 'sales_preorder', description: 'View commercial offers' },
  { code: PermissionCodes.SALES_OFFER_CREATE, module: 'sales_preorder', description: 'Create commercial offers' },
  { code: PermissionCodes.SALES_OFFER_EDIT, module: 'sales_preorder', description: 'Edit commercial offers' },
  { code: PermissionCodes.SALES_OFFER_SEND, module: 'sales_preorder', description: 'Send a commercial offer to the customer' },
  { code: PermissionCodes.SALES_OFFER_ACCEPT, module: 'sales_preorder', description: 'Mark a commercial offer accepted/rejected' },
  { code: PermissionCodes.SALES_OFFER_CANCEL, module: 'sales_preorder', description: 'Cancel a commercial offer' },
  { code: PermissionCodes.SALES_OFFER_CONVERT, module: 'sales_preorder', description: 'Convert an offer into a customer order' },
  { code: PermissionCodes.SALES_ORDER_CONFIRM, module: 'sales_preorder', description: 'Confirm a customer order' },
  { code: PermissionCodes.SALES_ORDER_CANCEL, module: 'sales_preorder', description: 'Cancel a customer order' },
  { code: PermissionCodes.SALES_ORDER_REOPEN, module: 'sales_preorder', description: 'Reopen (unconfirm) a customer order' },
  { code: PermissionCodes.SALES_PRICE_OVERRIDE, module: 'sales_preorder', description: 'Override a resolved price' },
  { code: PermissionCodes.SALES_DISCOUNT_OVERRIDE, module: 'sales_preorder', description: 'Override a line/document discount' },
  { code: PermissionCodes.SALES_CREDIT_OVERRIDE, module: 'sales_preorder', description: 'Override a blocked credit check' },
  { code: PermissionCodes.SALES_RESERVATION_VIEW, module: 'sales_preorder', description: 'View stock reservations' },
  { code: PermissionCodes.SALES_RESERVATION_MANAGE, module: 'sales_preorder', description: 'Create/release stock reservations' },
  { code: PermissionCodes.SALES_SHIPMENT_PLAN_VIEW, module: 'sales_preorder', description: 'View shipment plans' },
  { code: PermissionCodes.SALES_SHIPMENT_PLAN_MANAGE, module: 'sales_preorder', description: 'Create/manage shipment plans' },
  { code: PermissionCodes.SALES_PAYMENT_SCHEDULE_VIEW, module: 'sales_preorder', description: 'View order payment schedules' },
  { code: PermissionCodes.SALES_FULFILLMENT_VIEW, module: 'sales_preorder', description: 'View order fulfillment status' },
  { code: PermissionCodes.SALES_ORDER_HOLD_MANAGE, module: 'sales_preorder', description: 'Place/release order holds' },

  { code: PermissionCodes.SALES_SHIPMENT_VIEW, module: 'sales_execution', description: 'View shipments' },
  { code: PermissionCodes.SALES_SHIPMENT_CREATE, module: 'sales_execution', description: 'Create shipments' },
  { code: PermissionCodes.SALES_SHIPMENT_EDIT, module: 'sales_execution', description: 'Edit shipments' },
  { code: PermissionCodes.SALES_SHIPMENT_CANCEL, module: 'sales_execution', description: 'Cancel shipments' },
  { code: PermissionCodes.SALES_INVOICE_REVERSE, module: 'sales_execution', description: 'Reverse a posted sales invoice' },
  { code: PermissionCodes.SALES_RETURN_VIEW, module: 'sales_execution', description: 'View sales returns' },
  { code: PermissionCodes.SALES_RETURN_CREATE, module: 'sales_execution', description: 'Create sales returns' },
  { code: PermissionCodes.SALES_RETURN_EDIT, module: 'sales_execution', description: 'Edit sales returns' },
  { code: PermissionCodes.SALES_ACCOUNTING_ENTRIES_VIEW, module: 'sales_execution', description: 'View accounting entries behind a sales document' },
  { code: PermissionCodes.SALES_TAX_DETAILS_VIEW, module: 'sales_execution', description: 'View tax calculation details behind a sales document' },

  { code: PermissionCodes.PURCHASE_REQUIREMENT_VIEW, module: 'procurement', description: 'View purchase requirements' },
  { code: PermissionCodes.PURCHASE_REQUIREMENT_CREATE, module: 'procurement', description: 'Create purchase requirements' },
  { code: PermissionCodes.PURCHASE_REQUIREMENT_EDIT, module: 'procurement', description: 'Edit purchase requirements' },
  { code: PermissionCodes.PURCHASE_REQUIREMENT_CANCEL, module: 'procurement', description: 'Cancel purchase requirements' },
  { code: PermissionCodes.PURCHASE_REQUIREMENT_APPROVE, module: 'procurement', description: 'Approve a purchase requirement (department head)' },
  { code: PermissionCodes.PURCHASE_REQUIREMENT_REJECT, module: 'procurement', description: 'Reject a purchase requirement' },
  { code: PermissionCodes.PURCHASE_ORDER_VIEW, module: 'procurement', description: 'View purchase orders' },
  { code: PermissionCodes.PURCHASE_ORDER_CREATE, module: 'procurement', description: 'Create purchase orders' },
  { code: PermissionCodes.PURCHASE_ORDER_EDIT, module: 'procurement', description: 'Edit purchase orders' },
  { code: PermissionCodes.PURCHASE_ORDER_APPROVE, module: 'procurement', description: 'Approve one step of a purchase order approval chain' },
  { code: PermissionCodes.PURCHASE_ORDER_REJECT, module: 'procurement', description: 'Reject a purchase order approval' },
  { code: PermissionCodes.PURCHASE_ORDER_CONFIRM, module: 'procurement', description: 'Confirm a purchase order (commercial commitment)' },
  { code: PermissionCodes.PURCHASE_ORDER_REOPEN, module: 'procurement', description: 'Reopen (unconfirm) a purchase order' },
  { code: PermissionCodes.PURCHASE_ORDER_CANCEL, module: 'procurement', description: 'Cancel a purchase order' },
  { code: PermissionCodes.PURCHASE_PRICE_OVERRIDE, module: 'procurement', description: 'Override a resolved purchase price' },
  { code: PermissionCodes.PURCHASE_SUPPLIER_SELECTION_VIEW, module: 'procurement', description: 'View supplier selection candidates' },
  { code: PermissionCodes.PURCHASE_SUPPLIER_SELECTION_MANAGE, module: 'procurement', description: 'Select/change a purchase order supplier' },
  { code: PermissionCodes.PURCHASE_EXPECTED_RECEIPT_VIEW, module: 'procurement', description: 'View expected supply/receipts' },
  { code: PermissionCodes.PURCHASE_PAYMENT_SCHEDULE_VIEW, module: 'procurement', description: 'View purchase order payment schedules' },
  { code: PermissionCodes.PURCHASE_PAYMENT_SCHEDULE_MANAGE, module: 'procurement', description: 'Generate purchase order payment schedules' },
  { code: PermissionCodes.PURCHASE_SUPPLY_PLANNING_VIEW, module: 'procurement', description: 'View demand coverage / supply planning' },
  { code: PermissionCodes.PURCHASE_SUPPLY_PEGGING_MANAGE, module: 'procurement', description: 'Create/remove demand-supply pegs' },
  { code: PermissionCodes.PURCHASE_ORDER_HOLD_MANAGE, module: 'procurement', description: 'Place/release purchase order holds' },
  { code: PermissionCodes.PURCHASE_SUPPLIER_PRODUCT_CODE_VIEW, module: 'procurement', description: 'View supplier product code mappings' },
  { code: PermissionCodes.PURCHASE_SUPPLIER_PRODUCT_CODE_MANAGE, module: 'procurement', description: 'Manage supplier product code mappings' },

  { code: PermissionCodes.PURCHASE_VIEW, module: 'purchase_execution', description: 'View goods receipts, purchase invoices, returns, and additional costs' },
  { code: PermissionCodes.PURCHASE_CREATE, module: 'purchase_execution', description: 'Create goods receipts, purchase invoices, and additional costs' },
  { code: PermissionCodes.PURCHASE_EDIT, module: 'purchase_execution', description: 'Edit draft goods receipts and purchase invoices' },
  { code: PermissionCodes.PURCHASE_RETURN, module: 'purchase_execution', description: 'Create purchase returns' },
  { code: PermissionCodes.PURCHASE_VIEW_ACCOUNTING, module: 'purchase_execution', description: 'View purchase reports and accounting entries' },
  { code: PermissionCodes.PURCHASE_PRICE_VIEW, module: 'purchase_execution', description: 'View and override price/tax/monetary fields on goods receipts' },
  { code: PermissionCodes.PURCHASE_RECEIPT_APPROVE, module: 'purchase_execution', description: 'Approve an over-delivery on a goods receipt' },
  { code: PermissionCodes.PURCHASE_RECEIPT_REJECT, module: 'purchase_execution', description: 'Reject an over-delivery on a goods receipt' },
  { code: PermissionCodes.PURCHASE_INVOICE_APPROVE, module: 'purchase_execution', description: 'Approve a purchase invoice price variance' },
  { code: PermissionCodes.PURCHASE_INVOICE_REJECT, module: 'purchase_execution', description: 'Reject a purchase invoice price variance' },

  { code: PermissionCodes.PAYMENT_REQUEST_VIEW, module: 'treasury', description: 'View payment requests' },
  { code: PermissionCodes.PAYMENT_REQUEST_CREATE, module: 'treasury', description: 'Create payment requests' },
  { code: PermissionCodes.PAYMENT_REQUEST_CANCEL, module: 'treasury', description: 'Cancel payment requests' },
  { code: PermissionCodes.PAYMENT_ORDER_VIEW, module: 'treasury', description: 'View payment orders' },
  { code: PermissionCodes.PAYMENT_ORDER_CREATE, module: 'treasury', description: 'Create payment orders' },
  { code: PermissionCodes.PAYMENT_ORDER_EDIT, module: 'treasury', description: 'Edit draft payment orders' },
  { code: PermissionCodes.PAYMENT_ORDER_APPROVE, module: 'treasury', description: 'Approve a payment order (finance)' },
  { code: PermissionCodes.PAYMENT_ORDER_REJECT, module: 'treasury', description: 'Reject a payment order' },
  { code: PermissionCodes.PAYMENT_ORDER_RECONCILE, module: 'treasury', description: 'Reconcile a posted payment order against a bank statement' },

  { code: PermissionCodes.INVENTORY_VIEW, module: 'inventory', description: 'View stock balances and movements for accessible warehouses' },
  { code: PermissionCodes.INVENTORY_VIEW_ALL_WAREHOUSES, module: 'inventory', description: 'View stock across all warehouses, not just assigned ones' },
  { code: PermissionCodes.INVENTORY_TRANSFER_CREATE, module: 'inventory', description: 'Create warehouse transfers' },
  { code: PermissionCodes.INVENTORY_TRANSFER_POST, module: 'inventory', description: 'Post/ship warehouse transfers' },
  { code: PermissionCodes.INVENTORY_TRANSFER_RECEIVE, module: 'inventory', description: 'Receive warehouse transfers at the destination' },
  { code: PermissionCodes.INVENTORY_INTERNAL_MOVE, module: 'inventory', description: 'Move stock between locations within a warehouse' },
  { code: PermissionCodes.INVENTORY_CONSUME, module: 'inventory', description: 'Post internal consumption documents' },
  { code: PermissionCodes.INVENTORY_WRITE_OFF, module: 'inventory', description: 'Create write-off/surplus inventory adjustments' },
  { code: PermissionCodes.INVENTORY_WRITE_OFF_APPROVE, module: 'inventory', description: 'Approve/post inventory adjustments' },
  { code: PermissionCodes.INVENTORY_STATUS_CHANGE, module: 'inventory', description: 'Transfer stock between quality/inventory statuses' },
  { code: PermissionCodes.INVENTORY_RESERVE, module: 'inventory', description: 'Reserve stock' },
  { code: PermissionCodes.INVENTORY_RELEASE_RESERVATION, module: 'inventory', description: 'Release stock reservations' },
  { code: PermissionCodes.INVENTORY_OVERRIDE_NEGATIVE, module: 'inventory', description: 'Override negative-stock blocking' },
  { code: PermissionCodes.INVENTORY_VIEW_SERIAL_HISTORY, module: 'inventory', description: 'View full movement history for a serial number' },
  { code: PermissionCodes.INVENTORY_VIEW_MOVEMENTS, module: 'inventory', description: 'View the inventory movement register' },
  { code: PermissionCodes.INVENTORY_UNPOST, module: 'inventory', description: 'Unpost inventory documents' },
  { code: PermissionCodes.INVENTORY_PERIOD_OVERRIDE, module: 'inventory', description: 'Post inventory documents into a closed period' },
  { code: PermissionCodes.INVENTORY_MANUAL_ADJUSTMENT, module: 'inventory', description: 'Manually adjust stock outside the normal document flow' },
];
