/**
 * Stable dimension codes (spec section 26) — the same set of subconto
 * definitions every tenant gets seeded with. Kept as constants (never a
 * hardcoded string scattered through services) so a typo becomes a
 * compile error, not a silent mismatch at posting time.
 */
export const DimensionCodes = {
  ORGANIZATION: 'ORGANIZATION',
  BRANCH: 'BRANCH',
  DEPARTMENT: 'DEPARTMENT',
  WAREHOUSE: 'WAREHOUSE',
  CASHBOX: 'CASHBOX',
  BANK_ACCOUNT: 'BANK_ACCOUNT',
  PARTNER: 'PARTNER',
  COUNTERPARTY: 'COUNTERPARTY',
  CONTRACT: 'CONTRACT',
  AGREEMENT: 'AGREEMENT',
  PRODUCT: 'PRODUCT',
  PRODUCT_CHARACTERISTIC: 'PRODUCT_CHARACTERISTIC',
  CURRENCY: 'CURRENCY',
  SETTLEMENT_DOCUMENT: 'SETTLEMENT_DOCUMENT',
  // Fixed Assets (docx spec Phase 16, section 87)
  FIXED_ASSET: 'FIXED_ASSET',
} as const;

export type DimensionCode = (typeof DimensionCodes)[keyof typeof DimensionCodes];

/** Reference-entity type recorded on each dimension value (spec section 30
 * "never store arbitrary entity IDs without type enforcement") — deliberately
 * the same string as the dimension code for the entities we seed, since each
 * seeded dimension maps 1:1 to exactly one entity type today. */
export const DIMENSION_REFERENCE_ENTITY_TYPE: Record<string, string> = {
  [DimensionCodes.ORGANIZATION]: 'ORGANIZATION',
  [DimensionCodes.BRANCH]: 'BRANCH',
  [DimensionCodes.DEPARTMENT]: 'DEPARTMENT',
  [DimensionCodes.WAREHOUSE]: 'WAREHOUSE',
  [DimensionCodes.CASHBOX]: 'CASHBOX',
  [DimensionCodes.BANK_ACCOUNT]: 'BANK_ACCOUNT',
  [DimensionCodes.PARTNER]: 'COUNTERPARTY',
  [DimensionCodes.COUNTERPARTY]: 'COUNTERPARTY',
  [DimensionCodes.CONTRACT]: 'COUNTERPARTY',
  [DimensionCodes.AGREEMENT]: 'COUNTERPARTY',
  [DimensionCodes.PRODUCT]: 'PRODUCT',
  [DimensionCodes.PRODUCT_CHARACTERISTIC]: 'PRODUCT',
  [DimensionCodes.CURRENCY]: 'CURRENCY',
  [DimensionCodes.SETTLEMENT_DOCUMENT]: 'SETTLEMENT_DOCUMENT',
  [DimensionCodes.FIXED_ASSET]: 'FIXED_ASSET',
};

/**
 * Semantic accounting-mapping keys (spec sections 39-40) — business modules
 * resolve through AccountingMappingService.resolve(...) using one of these,
 * never a literal account code.
 */
export const MappingKeys = {
  CASH: 'CASH',
  BANK: 'BANK',
  MATERIAL_INVENTORY: 'MATERIAL_INVENTORY',
  FINISHED_GOODS: 'FINISHED_GOODS',
  GOODS_INVENTORY: 'GOODS_INVENTORY',
  CUSTOMER_RECEIVABLE: 'CUSTOMER_RECEIVABLE',
  SUPPLIER_ADVANCE: 'SUPPLIER_ADVANCE',
  CUSTOMER_ADVANCE: 'CUSTOMER_ADVANCE',
  SUPPLIER_PAYABLE: 'SUPPLIER_PAYABLE',
  SALES_REVENUE: 'SALES_REVENUE',
  SALES_RETURN: 'SALES_RETURN',
  SALES_DISCOUNT: 'SALES_DISCOUNT',
  COGS: 'COGS',
  COMMERCIAL_EXPENSE: 'COMMERCIAL_EXPENSE',
  ADMIN_EXPENSE: 'ADMIN_EXPENSE',
  OTHER_OPERATING_INCOME: 'OTHER_OPERATING_INCOME',
  OTHER_OPERATING_EXPENSE: 'OTHER_OPERATING_EXPENSE',
  CURRENT_INCOME_TAX_EXPENSE: 'CURRENT_INCOME_TAX_EXPENSE',
  // Tax Engine build (docx spec Phase 5, section 38)
  VAT_INPUT_RECOVERABLE: 'VAT_INPUT_RECOVERABLE',
  VAT_INPUT_PENDING: 'VAT_INPUT_PENDING',
  VAT_INPUT_NONRECOVERABLE: 'VAT_INPUT_NONRECOVERABLE',
  VAT_OUTPUT_PAYABLE: 'VAT_OUTPUT_PAYABLE',
  VAT_DEPOSIT_ACCOUNT: 'VAT_DEPOSIT_ACCOUNT',
  VAT_SETTLEMENT: 'VAT_SETTLEMENT',
  VAT_ROUNDING: 'VAT_ROUNDING',
  VAT_ADJUSTMENT: 'VAT_ADJUSTMENT',
  // Purchase / Procurement build (docx spec Phase 9, section 5 Model A)
  GOODS_RECEIVED_NOT_INVOICED: 'GOODS_RECEIVED_NOT_INVOICED',
  // Fixed Assets (docx spec Phase 16, section 86)
  FA_COST: 'FA_COST',
  FA_CIP: 'FA_CIP',
  FA_ACCUMULATED_DEPRECIATION: 'FA_ACCUMULATED_DEPRECIATION',
  FA_ACCUMULATED_IMPAIRMENT: 'FA_ACCUMULATED_IMPAIRMENT',
  FA_DEPRECIATION_EXPENSE: 'FA_DEPRECIATION_EXPENSE',
  FA_DEPRECIATION_EXPENSE_SALES: 'FA_DEPRECIATION_EXPENSE_SALES',
  FA_DEPRECIATION_EXPENSE_PRODUCTION: 'FA_DEPRECIATION_EXPENSE_PRODUCTION',
  FA_DEPRECIATION_EXPENSE_OTHER: 'FA_DEPRECIATION_EXPENSE_OTHER',
  FA_IMPAIRMENT_LOSS: 'FA_IMPAIRMENT_LOSS',
  FA_IMPAIRMENT_REVERSAL_GAIN: 'FA_IMPAIRMENT_REVERSAL_GAIN',
  FA_REVALUATION_RESERVE: 'FA_REVALUATION_RESERVE',
  FA_REVALUATION_LOSS: 'FA_REVALUATION_LOSS',
  FA_DISPOSAL_GAIN: 'FA_DISPOSAL_GAIN',
  FA_DISPOSAL_LOSS: 'FA_DISPOSAL_LOSS',
  FA_DISPOSAL_PROCEEDS: 'FA_DISPOSAL_PROCEEDS',
  FA_NON_CAPITALIZABLE_EXPENSE: 'FA_NON_CAPITALIZABLE_EXPENSE',
  FA_REPAIR_EXPENSE: 'FA_REPAIR_EXPENSE',
  FA_OPENING_BALANCE_OFFSET: 'FA_OPENING_BALANCE_OFFSET',
} as const;

export type MappingKey = (typeof MappingKeys)[keyof typeof MappingKeys];
